CREATE TABLE IF NOT EXISTS users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Address VARCHAR(200) NOT NULL,
    Mobile VARCHAR(15) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Eircode VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS appliances (
    ApplianceID INT AUTO_INCREMENT PRIMARY KEY,
    ApplianceType VARCHAR(50) NOT NULL,
    Brand VARCHAR(50) NOT NULL,
    ModelNumber VARCHAR(20) NOT NULL,
    SerialNumber VARCHAR(20) NOT NULL UNIQUE,
    PurchaseDate DATE NOT NULL,
    WarrantyExpirationDate DATE NOT NULL,
    CostOfAppliance DECIMAL(10, 2) NOT NULL,
    UserID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES users (UserID) ON DELETE CASCADE
);